name = "ParallelMCMC"
uuid = "1a970f40-4406-51c9-a967-cb3143c111e8"
version = "0.1.0"
authors = ["Ryan Senne <rsenne@bu.edu>"]

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
AbstractMCMC = "5.10.0"
DifferentiationInterface = "0.7.13"
Distributions = "0.25.122"
LinearAlgebra = "1.12.0"
LogExpFunctions = "0.3.29"
MCMCChains = "7.7.0"
Mooncake = "0.4.192"
Random = "1.11.0"
Statistics = "1.11.1"
julia = "1.10"
